export const ApiStatusMessage = {
  STATUS_CODE_200: 'OK',
  STATUS_CODE_201: 'Created',
  STATUS_CODE_202: 'Accepted',
  STATUS_CODE_204: 'No Content',
  STATUS_CODE_400: 'Bad Request',
  STATUS_CODE_401: 'Unauthorized',
  STATUS_CODE_403: 'Forbidden',
  STATUS_CODE_404: 'Not Found',
  STATUS_CODE_405: 'Method Not Allowed',
  STATUS_CODE_409: 'Conflict',
  STATUS_CODE_422: 'Unprocessable Entity',
  STATUS_CODE_429: 'Too Many Requests',
  STATUS_CODE_500: 'Internal Server Error',
  STATUS_CODE_501: 'Not Implemented',
  STATUS_CODE_502: 'Bad Gateway',
  STATUS_CODE_503: 'Service Unavailable',
  STATUS_CODE_504: 'Gateway Timeout',
};
