import {
  IconAffiliate,
  IconAlertTriangle,
  IconAlignCenter,
  IconAlignLeft,
  IconAlignRight,
  IconAppWindow,
  IconArrowBarToRight,
  IconArrowDown,
  IconArrowLeft,
  IconArrowNarrowRight,
  IconArrowRight,
  IconBorderBottom,
  IconBorderCorners,
  IconBorderLeft,
  IconBorderRight,
  IconBorderSides,
  IconBorderTop,
  IconBox,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconBoxAlignRight,
  IconBoxAlignTop,
  IconBoxMargin,
  IconBoxPadding,
  IconBrandGithub,
  IconBrush,
  IconCalendar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronUp,
  IconComet,
  IconComponents,
  IconCopy,
  IconCross,
  IconDatabase,
  IconFile,
  IconFileTypography,
  IconGlobe,
  IconGolf,
  IconHash,
  IconHeart,
  IconInfoCircle,
  IconLayout,
  IconLayoutAlignBottom,
  IconLayoutAlignCenter,
  IconLayoutAlignLeft,
  IconLayoutAlignMiddle,
  IconLayoutAlignRight,
  IconLayoutAlignTop,
  IconLayoutDistributeHorizontal,
  IconLayoutDistributeVertical,
  IconLayoutOff,
  IconLineDashed,
  IconLineDotted,
  IconLink,
  IconList,
  IconLoader,
  IconLogout,
  IconMaximize,
  IconMoon,
  IconPhoto,
  IconPlus,
  IconPuzzle,
  IconRadiusBottomLeft,
  IconRadiusBottomRight,
  IconRadiusTopLeft,
  IconRadiusTopRight,
  IconSchema,
  IconSearch,
  IconSend,
  IconSettings,
  IconSparkles,
  IconSun,
  IconSunMoon,
  IconToggleLeft,
  IconTopologyStar3,
  IconTrash,
  IconUser,
  IconWand,
  IconX,
} from "@tabler/icons-react";

export const Icons = {
  Brush: IconBrush,
  Layout: IconLayout,
  LayoutOff: IconLayoutOff,
  BoxMargin: IconBoxMargin,
  BoxPadding: IconBoxPadding,
  BorderTop: IconBorderTop,
  BorderRight: IconBorderRight,
  BorderBottom: IconBorderBottom,
  BorderLeft: IconBorderLeft,
  LineDashed: IconLineDashed,
  LineDotted: IconLineDotted,
  Hash: IconHash,
  Maximize: IconMaximize,
  BorderCorners: IconBorderCorners,
  BorderSides: IconBorderSides,
  AlignLeft: IconAlignLeft,
  AlignRight: IconAlignRight,
  AlignCenter: IconAlignCenter,
  BoxAlignTop: IconBoxAlignTop,
  BoxAlignBottom: IconBoxAlignBottom,
  BoxAlignRight: IconBoxAlignRight,
  BoxAlignLeft: IconBoxAlignLeft,
  User: IconUser,
  TopologyStar3: IconTopologyStar3,
  AlertTriangle: IconAlertTriangle,
  ToggleLeft: IconToggleLeft,
  Calendar: IconCalendar,
  Link: IconLink,
  List: IconList,
  Box: IconBox,
  FileTypography: IconFileTypography,
  Photo: IconPhoto,
  File: IconFile,
  Send: IconSend,
  ArrowDown: IconArrowDown,
  LayoutDistributeVertical: IconLayoutDistributeVertical,
  LayoutDistributeHorizontal: IconLayoutDistributeHorizontal,
  LayoutAlignLeft: IconLayoutAlignLeft,
  LayoutAlignRight: IconLayoutAlignRight,
  LayoutAlignMiddle: IconLayoutAlignMiddle,
  LayoutAlignTop: IconLayoutAlignTop,
  LayoutAlignBottom: IconLayoutAlignBottom,
  LayoutAlignCenter: IconLayoutAlignCenter,
  RadiusTopLeft: IconRadiusTopLeft,
  RadiusTopRight: IconRadiusTopRight,
  RadiusBottomRight: IconRadiusBottomRight,
  RadiusBottomLeft: IconRadiusBottomLeft,
  Wand: IconWand,
  ChevronUp: IconChevronUp,
  ChevronDown: IconChevronDown,
  Trash: IconTrash,
  InfoCircle: IconInfoCircle,
  X: IconX,
  Cross: IconCross,
  AppWindow: IconAppWindow,
  Settings: IconSettings,
  Affiliate: IconAffiliate,
  Globe: IconGlobe,
  Components: IconComponents,
  SignOut: IconLogout,
  Schema: IconSchema,
  Golf: IconGolf,
  BrandGithub: IconBrandGithub,
  Database: IconDatabase,
  ArrowBarToRight: IconArrowBarToRight,
  Copy: IconCopy,
  Check: IconCheck,
  Loader: IconLoader,
  Plus: IconPlus,
  ChevronLeft: IconChevronLeft,
  ArrowNarrowRight: IconArrowNarrowRight,
  ArrowRight: IconArrowRight,
  Comet: IconComet,
  Puzzle: IconPuzzle,
  ArrowLeft: IconArrowLeft,
  Heart: IconHeart,
  Search: IconSearch,
  Sun: IconSun,
  Moon: IconMoon,
  SunMoon: IconSunMoon,
  Sparkles: IconSparkles,
};
